name: ml_automation_workflow

on:
    workflow_dispatch:

jobs:
    image-build:
        - name: Build Docker Image
          run: |
              docker build -t ml_automation .
        
    image-run:
        - name: Run Docker Container
          run: |
              docker run -d --name ml_automation_container ml_automation
        depends-on: image-build
